module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        display: ['"Plus Jakarta Sans"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        body: ['"Plus Jakarta Sans"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      colors: {
        page: 'var(--bg-page)',
        'page-alt': 'var(--bg-page-alt)',
        card: 'var(--surface-card)',
        sunken: 'var(--surface-sunken)',
        nav: 'var(--surface-nav)',
        'surface-hover': 'var(--surface-hover)',
        'surface-active': 'var(--surface-active)',
        strong: 'var(--text-strong)',
        body: 'var(--text-body)',
        muted: 'var(--text-muted)',
        subtle: 'var(--text-subtle)',
        'on-dark': 'var(--text-on-dark)',
        line: {
          subtle: 'var(--border-subtle)',
          strong: 'var(--border-strong)',
          dashed: 'var(--border-dashed)',
        },
        primary: {
          DEFAULT: 'var(--action-primary)',
          hover: 'var(--action-primary-hover)',
          text: 'var(--action-primary-text)',
        },
        secondary: {
          bg: 'var(--action-secondary-bg)',
          border: 'var(--action-secondary-border)',
          text: 'var(--action-secondary-text)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          soft: 'var(--accent-soft)',
        },
        focus: 'var(--focus-ring)',
        bronze: {
          200: 'var(--bronze-200)',
          600: 'var(--bronze-600)',
        },
        status: {
          'blue-bg': 'var(--status-blue-bg)',
          blue: 'var(--status-blue)',
          'green-bg': 'var(--status-green-bg)',
          green: 'var(--status-green)',
          'amber-bg': 'var(--status-amber-bg)',
          'red-bg': 'var(--status-red-bg)',
          red: 'var(--status-red)',
        },
      },
      borderRadius: {
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '20px',
        xl: '26px',
        '2xl': '32px',
        button: '14px',
        input: '14px',
        card: '20px',
        panel: '26px',
        dropzone: '22px',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        float: 'var(--shadow-float)',
      },
      ringColor: {
        focus: 'var(--focus-ring)',
      },
    },
  },
  plugins: [],
}
